apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- filestash-rollout.yaml
- filestash-service.yaml
- filestash-preview-service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: kubecon-demo-filestash-cm
  files:
  - kubecon-demo-filestash-config.json

# Upgrade to new version
# images:
# - name: machines/filestash
#   newName: alexmt/filestash
#   newTag: v0.1
